---
title: "git_00"
author: "Vanessa Alejandre"
date: "June 1, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make.   
      The billows smooth and bright —  
And this was odd, because it was   
      The middle of the night  
      
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,   
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was   
      the middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
My first trip, I scoured every floor  
of the MoMA, winding around other patrons  
before they could read “Alabama” on my tee.  
I lingered over Birthday’s lovers  
levitating into kiss, then moved as if driven  
until I found, unreal and gleaming,  
an Airstream. I made myself at home.  
I took a seat. I cranked the slatted glass  
open and peered out at the nearby Eames  
and Starck. You’d think I had never seen  
metal rivets before. I had never seen anything  
from where I come from hailed as art. I want that  
trailer-inside-the-MoMA feeling again now, I want  
dandelion seed valued as much as tulip bulbs.  
So I’m buying this packet of what most want  
to poison. And the dream of putting down  
roots. It has nothing to do with dandelions  
that sprout and blossom into suns and moons  
as bright and mythic as any Chagall.  